import { Event, College, Category } from './types';

export const COLLEGES: College[] = [
  { id: 'c1', name: 'St. Horizon University', approved: true },
  { id: 'c2', name: 'Northridge Institute of Technology', approved: true },
  { id: 'c3', name: 'Crestview College of Arts', approved: true },
  { id: 'c4', name: 'Maplewood Community College', approved: false },
];

export const CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Tech' },
  { id: 'cat2', name: 'Arts' },
  { id: 'cat3', name: 'Sports' },
  { id: 'cat4', name: 'E-Sports' },
];

export const EVENTS: Event[] = [
  {
    id: 'e1',
    name: 'Hackathon 2024',
    description: 'A 24-hour coding competition to build innovative solutions.',
    longDescription: 'Join us for the most anticipated tech event of the year! Hackathon 2024 brings together the brightest minds to solve real-world problems. Whether you are a seasoned developer or a curious beginner, this is your platform to innovate, collaborate, and create. Food, drinks, and mentorship provided throughout the event.',
    collegeId: 'c2',
    categoryId: 'cat1',
    date: '2024-10-26',
    time: '09:00 AM - 09:00 AM (Next Day)',
    location: 'Tech Dome, NIT Campus',
    imageUrl: 'https://picsum.photos/seed/hackathon/600/400',
    participants: [
      { id: 'p1', name: 'Alice Johnson', avatarUrl: 'https://i.pravatar.cc/150?u=p1' },
      { id: 'p2', name: 'Bob Williams', avatarUrl: 'https://i.pravatar.cc/150?u=p2' },
      { id: 'p3', name: 'Charlie Brown', avatarUrl: 'https://i.pravatar.cc/150?u=p3' },
    ],
    rules: [
      'Teams can have 2-4 members.',
      'All code must be written during the event.',
      'Use of open-source libraries is permitted.',
      'Final submissions must include a demo video.',
    ],
    prize: '$5,000 Cash Prize + Internships',
  },
  {
    id: 'e2',
    name: 'Artistry in Motion',
    description: 'An exhibition of student paintings, sculptures, and digital art.',
    longDescription: 'Immerse yourself in a world of creativity at Artistry in Motion. This exhibition showcases the incredible talent of our student artists. From classical paintings to modern digital installations, experience a diverse range of artistic expressions. The event will also feature live artist talks and interactive workshops.',
    collegeId: 'c3',
    categoryId: 'cat2',
    date: '2024-11-05',
    time: '10:00 AM - 06:00 PM',
    location: 'Grand Art Gallery, Crestview Campus',
    imageUrl: 'https://picsum.photos/seed/art/600/400',
    participants: [
      { id: 'p4', name: 'Diana Prince', avatarUrl: 'https://i.pravatar.cc/150?u=p4' },
      { id: 'p5', name: 'Eve Adams', avatarUrl: 'https://i.pravatar.cc/150?u=p5' },
    ],
    rules: [
      'Artwork must be original.',
      'Submissions must be made by the deadline.',
      'Artists must be present during the opening reception.',
    ],
    prize: 'Featured gallery spot + $1,000 grant',
  },
  {
    id: 'e3',
    name: 'University Soccer League Finals',
    description: 'The final match of the inter-college soccer tournament.',
    longDescription: 'Feel the adrenaline as the top two teams battle it out for the championship trophy in the University Soccer League Finals! Expect a thrilling match filled with passion, skill, and sportsmanship. Bring your friends and family to cheer for your favorite team. Pre-game festivities start at 5 PM.',
    collegeId: 'c1',
    categoryId: 'cat3',
    date: '2024-11-12',
    time: '06:00 PM',
    location: 'St. Horizon Stadium',
    imageUrl: 'https://picsum.photos/seed/soccer/600/400',
    participants: Array.from({ length: 22 }, (_, i) => ({ id: `ps${i}`, name: `Player ${i+1}`, avatarUrl: `https://i.pravatar.cc/150?u=ps${i}` })),
    rules: [
      'Standard FIFA rules apply.',
      'Players must adhere to the code of conduct.',
      'The referee\'s decision is final.',
    ],
    prize: 'Championship Trophy & Medals',
  },
  {
    id: 'e4',
    name: 'Tech Innovators Summit',
    description: 'A conference featuring talks from industry leaders in technology.',
    longDescription: 'Get inspired at the Tech Innovators Summit. This full-day conference hosts renowned speakers from leading tech companies who will share their insights on AI, blockchain, and the future of software development. An excellent networking opportunity for students and professionals alike.',
    collegeId: 'c2',
    categoryId: 'cat1',
    date: '2024-11-18',
    time: '09:00 AM - 05:00 PM',
    location: 'Auditorium Complex, NIT Campus',
    imageUrl: 'https://picsum.photos/seed/techsummit/600/400',
    participants: [],
    rules: [
      'Registration is mandatory for entry.',
      'Q&A sessions will follow each talk.',
      'Lunch and refreshments will be provided.',
    ],
    prize: 'Knowledge & Networking',
  },
  {
    id: 'e5',
    name: 'Valorant Invitational',
    description: 'Top college teams compete in this premier Valorant tournament.',
    longDescription: 'Witness tactical genius and incredible skill at the Valorant Invitational. The best collegiate e-sports teams will face off for glory and prizes. Matches will be live-streamed with professional casters. Join the hype and support your college team!',
    collegeId: 'c1',
    categoryId: 'cat4',
    date: '2024-11-22',
    time: '12:00 PM onwards',
    location: 'E-Sports Arena, St. Horizon University',
    imageUrl: 'https://picsum.photos/seed/esports/600/400',
    participants: Array.from({ length: 20 }, (_, i) => ({ id: `pe${i}`, name: `Gamer ${i+1}`, avatarUrl: `https://i.pravatar.cc/150?u=pe${i}` })),
    rules: [
      'Standard competitive Valorant rules.',
      'Teams of 5 players.',
      'All participants must be enrolled students.',
    ],
    prize: '$2,500 Prize Pool',
  },
  {
    id: 'e6',
    name: 'Annual Theatre Festival',
    description: 'A week-long showcase of plays and dramas by student clubs.',
    longDescription: 'The stage is set for the Annual Theatre Festival! Experience a captivating lineup of performances, from timeless classics to contemporary original scripts. Each night features a different play, directed and performed entirely by students. A celebration of storytelling and dramatic arts.',
    collegeId: 'c3',
    categoryId: 'cat2',
    date: '2024-12-01',
    time: '07:00 PM nightly',
    location: 'Preston Hall, Crestview Campus',
    imageUrl: 'https://picsum.photos/seed/theatre/600/400',
    participants: [],
    rules: [
      'Tickets can be booked online or at the venue.',
      'Late entry is not permitted.',
      'Photography and recording are prohibited during performances.',
    ],
    prize: 'Best Play & Best Actor Awards',
  },
];